version: '3.8'

services:
  verifyface:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    container_name: verifyface-container
    environment:
      - FLASK_ENV=development